apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-minio
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: kubeflow-minio
subjects:
- kind: ServiceAccount
  name: kubeflow-minio
  namespace: kubeflow