apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccount: kubeflow-minio
      initContainers:
      - name: init
        image: minio-init
      containers:
      - args: null
        env:
        - name: MINIO_ACCESS_KEY
          $patch: delete
        - name: MINIO_SECRET_KEY
          $patch: delete
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: accesskey
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: secretkey
        image: minio
        name: minio
