apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- cr.yaml
- crb.yaml
patchesStrategicMerge:
- deployment.yaml

images:
- name: minio-init
  newName: $(airgapRegistry)gcr.io/mapr-252711/kubeflow/minio/init
  newTag: latestC
- name: minio
  newName: $(airgapRegistry)gcr.io/mapr-252711/kubeflow/minio/server
  newTag: latestC

configurations:
- params.yaml
