apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-eventing
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- secret.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newTag: v0.14.2
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/channel_broker
  newName: $(airgapRegistry)gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_broker
  newTag: v1.3.0-branch-hpe
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newTag: v0.14.2
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller
  newName: $(airgapRegistry)gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_controller
  newTag: v1.3.0-branch-hpe
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher
  newName: $(airgapRegistry)gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_dispatcher
  newTag: v1.3.0-branch-hpe

configMapGenerator:
- name: knative-eventing-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: knative-eventing-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml
