apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-eventing
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- secret.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newTag: v0.14.2
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/channel_broker
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/channel_broker
  digest: sha256:5065eaeb3904e8b0893255b11fdcdde54a6bac1d0d4ecc8c9ce4c4c32073d924
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newTag: v0.14.2
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller
  digest: sha256:9a084ba0ed6a12862adb3ca00de069f0ec1715fe8d4db6c9921fcca335c675bb
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher
  digest: sha256:8df896444091f1b34185f0fa3da5d41f32e84c43c48df07605c728e0fe49a9a8

configMapGenerator:
- name: knative-eventing-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: knative-eventing-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml
