apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

configMapGenerator:
- name: notebook-controller-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: notebook-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY

configurations:
- params.yaml

images:
- name: gcr.io/mapr-252711/kf-ecp-5.3.0/notebook-controller
  newName: $(airgapRegistry)gcr.io/mapr-252711/kf-ecp-5.3.0/notebook-controller
  newTag: v1.3.0-branch-hpe-579067ec
