apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-grpc-configmap.yaml
  - metadata-grpc-deployment.yaml
  - metadata-grpc-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
  - metadata-grpc-sa.yaml
images:
  - name: gcr.io/ml-pipeline/metadata-envoy
    newName: $(airgapRegistry)gcr.io/ml-pipeline/metadata-envoy
    newTag: 1.5.0
  - name: gcr.io/tfx-oss-public/ml_metadata_store_server
    newName: $(airgapRegistry)gcr.io/tfx-oss-public/ml_metadata_store_server
    newTag: 0.25.1
configurations:
- params.yaml