apiVersion: v1
kind: ServiceAccount
metadata:
  name: imc-controller
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imc-dispatcher
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventing-controller
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets
