varReference:
- path: webhooks/clientConfig/service/name
  kind: MutatingWebhookConfiguration
- path: webhooks/clientConfig/service/namespace
  kind: MutatingWebhookConfiguration
- path: webhooks/clientConfig/service/name
  kind: ValidatingWebhookConfiguration
- path: webhooks/clientConfig/service/namespace
  kind: ValidatingWebhookConfiguration
- path: spec/conversion/webhookClientConfig/service/name
  kind: CustomResourceDefinition
- path: spec/conversion/webhookClientConfig/service/namespace
  kind: CustomResourceDefinition
- path: data/ingress
  kind: ConfigMap
- path: data/predictors
  kind: ConfigMap
- path: data/explainers
  kind: ConfigMap
- path: data/storageInitializer
  kind: ConfigMap
- path: data/logger
  kind: ConfigMap
- path: data/batcher
  kind: ConfigMap
- path: data/agent
  kind: ConfigMap
- path: spec/template/spec/containers/image
  kind: StatefulSet