apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namespace: kubeflow
namePrefix: xgboost-operator-
configMapGenerator:
- envs:
  - params.env
  name: xgboost-operator-config
images:
- name: gcr.io/kubeflow-images-public/xgboost-operator
  newName: $(airgapRegistry)kubeflow/xgboost-operator
  newTag: v0.2.0

generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: xgboost-operator-config
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml
