varReference:
- path: spec/configPatches/patch/value/typed_config/http_service/server_uri/uri
  kind: EnvoyFilter
- path: spec/configPatches/patch/value/typed_config/http_service/server_uri/cluster
  kind: EnvoyFilter
- path: spec/template/spec/containers/image
  kind: StatefulSet
