apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
- literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  name: zeppelin-operator-config
