apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/serving-core.yaml
- upstream/net-istio.yaml
- istio-authorization-policy.yaml
patchesStrategicMerge:
- patches/configmap-patch.yaml
- patches/namespace-injection.yaml
- patches/clusterrole-patch.yaml
patches:
- path: patches/sidecar-injection.yaml
  target:
    kind: Deployment
    
images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/serving/cmd/activator
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/serving/cmd/webhook
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/serving/cmd/controller
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: $(airgapRegistry)gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook

configMapGenerator:
- name: knative-serving-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: knative-serving-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml
