apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: controller
        env:
        - name: http_proxy
          value: $(http_proxy)
        - name: https_proxy
          value: $(https_proxy)
        - name: no_proxy
          value: $(no_proxy)
