apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-minio-console
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: kubeflow-minio-console
subjects:
- kind: ServiceAccount
  name: kubeflow-minio-console
  namespace: kubeflow
