apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccount: kubeflow-minio
      initContainers:
      - name: wait
        image: wait-script
        env:
        - name: MINIO_ENDPOINT
          value: minio-service.kubeflow.svc.cluster.local
        - name: MINIO_PORT
          value: '9000'
      containers:
      - name: minio-console
        image: minio-console
        env:
        - name: KF_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ENDPOINT
          value: minio-service.kubeflow.svc.cluster.local
        - name: MINIO_PORT
          value: '9000'
        ports:
        - containerPort: 9090
