apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: minio-console
resources:
- service-account.yaml
- cr.yaml
- crb.yaml
- deployment.yaml
- service.yaml
namespace: kubeflow
configMapGenerator:
- name: pipeline-minio-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: pipeline-minio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
images:
- name: minio-console
  newTag: latestC
  newName: $(airgapRegistry)gcr.io/mapr-252711/kubeflow/minio/console
- name: wait-script
  newTag: latestC
  newName: $(airgapRegistry)gcr.io/mapr-252711/kubeflow/minio/wait-script
configurations:
- params.yaml
