apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  type: NodePort
