apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: profile-controller
        image: python:3.7
        command: ["python", "/hooks/sync.py"]
        envFrom:
        - configMapRef:
            name: kubeflow-pipelines-profile-controller-env
        env:
        - name: KFP_VERSION
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: appVersion
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: secretkey
        - name: MINIO_HOST
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: host
        - name: MINIO_PORT
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: port
        - name: MINIO_SECURE
          valueFrom:
            secretKeyRef:
              name: minio-params
              key: secure
        - name: airgapRegistry
          value: $(airgapRegistry)
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        ports:
        - containerPort: 8080
      volumes:
      - name: hooks
        configMap:
          name: kubeflow-pipelines-profile-controller-code
