apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  app: mxnet-operator
  app.kubernetes.io/component: mxnet
  app.kubernetes.io/name: mxnet-operator
  kustomize.component: mxnet-operator

resources:
- crd-v1.yaml

patchesStrategicMerge:
  - deployment.yaml

images:
- name: kubeflow/mxnet-operator
  newName: $(airgapRegistry)kubeflow/mxnet-operator

configMapGenerator:
- name: mxnet-operator-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: mxnet-operator-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml