apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kfserving-system
data:
  predictors: |-
    {
        "tensorflow": {
            "image": "$(airgapRegistry)tensorflow/serving",
            "defaultImageVersion": "1.14.0",
            "defaultGpuImageVersion": "1.14.0-gpu",
            "defaultTimeout": "60",
            "supportedFrameworks": [
              "tensorflow"
            ],
            "multiModelServer": false
        },
        "onnx": {
            "image": "$(airgapRegistry)mcr.microsoft.com/onnxruntime/server",
            "defaultImageVersion": "v1.0.0",
            "supportedFrameworks": [
              "onnx"
            ],
            "multiModelServer": false
        },
        "sklearn": {
          "v1": {
            "image": "$(airgapRegistry)gcr.io/kfserving/sklearnserver",
            "defaultImageVersion": "v0.5.1",
            "supportedFrameworks": [
              "sklearn"
            ],
            "multiModelServer": false
          },
          "v2": {
            "image": "$(airgapRegistry)docker.io/seldonio/mlserver",
            "defaultImageVersion": "0.2.1",
            "supportedFrameworks": [
              "sklearn"
            ],
            "multiModelServer": false
          }
        },
        "xgboost": {
          "v1": {
            "image": "$(airgapRegistry)gcr.io/kfserving/xgbserver",
            "defaultImageVersion": "v0.5.1",
            "supportedFrameworks": [
              "xgboost"
            ],
            "multiModelServer": false
          },
          "v2": {
            "image": "$(airgapRegistry)docker.io/seldonio/mlserver",
            "defaultImageVersion": "0.2.1",
            "supportedFrameworks": [
              "xgboost"
            ],
            "multiModelServer": false
          }
        },
        "pytorch": {
          "v1" : {
            "image": "$(airgapRegistry)gcr.io/kfserving/pytorchserver",
            "defaultImageVersion": "v0.5.1",
            "defaultGpuImageVersion": "v0.5.1-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          },
          "v2" : {
            "image": "$(airgapRegistry)kfserving/torchserve-kfs",
            "defaultImageVersion": "0.3.0",
            "defaultGpuImageVersion": "0.3.0-gpu",
            "supportedFrameworks": [
              "pytorch"
            ],
            "multiModelServer": false
          }
        },
        "triton": {
            "image": "$(airgapRegistry)nvcr.io/nvidia/tritonserver",
            "defaultImageVersion": "20.08-py3",
            "supportedFrameworks": [
              "tensorrt",
              "tensorflow",
              "onnx",
              "pytorch",
              "caffe2"
            ],
            "multiModelServer": false
        },
        "pmml": {
            "image": "$(airgapRegistry)kfserving/pmmlserver",
            "defaultImageVersion": "v0.5.1",
            "supportedFrameworks": [
              "pmml"
            ],
            "multiModelServer": false
        },
        "lightgbm": {
            "image": "$(airgapRegistry)kfserving/lgbserver",
            "defaultImageVersion": "v0.5.1",
            "supportedFrameworks": [
              "lightgbm"
            ],
            "multiModelServer": false
        }
    }
  transformers: |-
    {
    }
  explainers: |-
    {
        "alibi": {
            "image" : "$(airgapRegistry)kfserving/alibi-explainer",
            "defaultImageVersion": "v0.5.1"
        },
        "aix": {
            "image" : "$(airgapRegistry)kfserving/aix-explainer",
            "defaultImageVersion": "v0.5.1"
        },
        "art": {
            "image" : "$(airgapRegistry)kfserving/art-explainer",
            "defaultImageVersion": "v0.5.1"
        }
    }
  storageInitializer: |-
    {
        "image" : "$(airgapRegistry)gcr.io/kfserving/storage-initializer:v0.5.1",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
  credentials: |-
    {
       "gcs": {
           "gcsCredentialFileName": "gcloud-application-credentials.json"
       },
       "s3": {
           "s3AccessKeyIDName": "AWS_ACCESS_KEY_ID",
           "s3SecretAccessKeyName": "AWS_SECRET_ACCESS_KEY"
       }
    }
  ingress: |-
    {
        "ingressGateway" : $(ingressGateway)
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "cluster-local-gateway.knative-serving",
        "localGatewayService" : "cluster-local-gateway.istio-system.svc.cluster.local"
    }
  logger: |-
    {
        "image" : "$(airgapRegistry)kfserving/agent:v0.5.1",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "defaultUrl": "http://default-broker"
    }
  batcher: |-
    {
        "image" : "$(airgapRegistry)kfserving/agent:v0.5.1",
        "memoryRequest": "1Gi",
        "memoryLimit": "1Gi",
        "cpuRequest": "1",
        "cpuLimit": "1"
    }
  agent: |-
    {
        "image" : "$(airgapRegistry)kfserving/agent:v0.5.1",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
