---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-gatekeeper
spec:
  type: NodePort
  ports:
    - port: 5554
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: keycloak-gatekeeper
