apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../image-pull-secret
- service.yaml
- virtual-service.yaml

commonLabels:
  kustomize.component: profiles

patchesStrategicMerge:
- patches/kfam.yaml
- patches/remove-namespace.yaml

configMapGenerator:
- name: profiles-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- name: PROFILES_NAMESPACE
  fieldref:
    fieldpath: metadata.namespace
  objref:
    name: profiles-kfam
    kind: Service
    apiVersion: v1
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: $(airgapRegistry)public.ecr.aws/j1r0q0g6/notebooks/access-management
  newTag: v1.3.0-rc.1
