apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml
- gateway_authorizationpolicy.yaml
- deny_all_authorizationpolicy.yaml
- gateway.yaml
- x-forwarded-host.yaml

namespace: istio-system

patchesStrategicMerge:
- patches/service.yaml
- patches/remove-pdb.yaml

configMapGenerator:
- name: istio-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml

images:
- name: docker.io/istio/proxyv2
  newName: $(airgapRegistry)istio/proxyv2
  newTag: 1.9.0
- name: docker.io/istio/pilot
  newName: $(airgapRegistry)istio/pilot
  newTag: 1.9.0