apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eventing.knative.dev/release: v0.14.2
  name: imc-controller
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eventing.knative.dev/release: v0.14.2
  name: imc-dispatcher
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eventing.knative.dev/release: v0.14.2
  name: eventing-controller
  namespace: knative-eventing
imagePullSecrets:
- name: hpe-imagepull-secrets