apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prism-local
  namespace: $(namespace)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prism-local
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
