apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prism-local
  namespace: $(namespace)
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - bindings
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - pods/exec
  - pods/log
  - pods/portforward
  verbs:
  - '*'
