apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism
  namespace: $(namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prism
  template:
    metadata:
      labels:
        name: prism
    spec:
      serviceAccountName: prism
      containers:
        - name: prism
          # Replace this with the built image name
          image: bluedata/prism
          command:
          - prism
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prism"
