kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prism
subjects:
- kind: ServiceAccount
  name: prism
  namespace: $(namespace)
roleRef:
  kind: ClusterRole
  name: prism
  apiGroup: rbac.authorization.k8s.io
