kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-init
subjects:
- kind: ServiceAccount
  name: argo
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: argo-init
  apiGroup: rbac.authorization.k8s.io
