kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-init
  namespace: kubeflow
subjects:
- kind: ServiceAccount
  name: argo
roleRef:
  kind: Role
  name: argo-init
  apiGroup: rbac.authorization.k8s.io
