apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      initContainers:
      - name: config
        image: argo-init
        volumeMounts:
        - mountPath: /etc/minio-params
          name: minio-params
      volumes:
      - name: minio-params
        secret:
          secretName: minio-params