apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    app.kubernetes.io/part-of: kubeflow
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: kubeflow-seldondeployment-rbac-edit
rules: 
- apiGroups:
  - machinelearning.seldon.io
  resources:
    - seldondeployments
  verbs: 
    - '*'
