# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- resources.yaml
- cluster-role.yaml

configurations:
  - kustomizeconfig.yaml
  - params.yaml

vars:
- name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: seldon-serving-cert # this name should match the one in certificate.yaml
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: seldon-serving-cert # this name should match the one in certificate.yaml
- name: SERVICE_NAMESPACE # namespace of the service
  objref:
    kind: Service
    version: v1
    name: seldon-webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: seldon-webhook-service
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: seldon-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY

configMapGenerator:
- name: seldon-parameters
  envs:
  - params.env

images:
- name: docker.io/seldonio/seldon-core-operator
  newName: $(airgapRegistry)docker.io/seldonio/seldon-core-operator
  newTag: 1.4.0
