apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: ldap-svc.hpe-ldap.svc.cluster.local:389
          insecureNoSSL: true
          insecureSkipVerify: true
          startTLS: false
          bindDN: cn=admin,dc=example,dc=com
          bindPW: mapr
          usernamePrompt: username
          userSearch:
            baseDN: ou=users,dc=example,dc=com
            filter: "(objectClass=inetOrgPerson)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: ou=groups,dc=example,dc=com
            filter: "(objectClass: groupOfNames)"
            userAttr: gidNumber
            groupAttr: gidNumber
            nameAttr: cn(base)
