apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zeppelins.zeppelin.hcp.hpe.com
spec:
  group: zeppelin.hcp.hpe.com
  names:
    kind: Zeppelin
    listKind: ZeppelinList
    plural: zeppelins
    singular: zeppelin
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
