apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zeppelin-operator
  template:
    metadata:
      labels:
        name: zeppelin-operator
    spec:
      serviceAccountName: zeppelin-operator
      containers:
        - name: zeppelin-operator
          image: gcr.io/mapr-252711/zeppelin-operator:0.1.0
          command:
          - zeppelin-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zeppelin-operator"
