apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- crd.yaml
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- deployment.yaml

images:
- name: gcr.io/mapr-252711/zeppelin-operator
  newName: $(airgapRegistry)gcr.io/mapr-252711/zeppelin-operator
  newTag: "0.1.0"

configMapGenerator:
- name: zeppelin-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: zeppelin-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.airgapRegistry
configurations:
- params.yaml
