apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
- name: knative-serving-proxy
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: http_proxy
  objref:
    kind: ConfigMap
    name: knative-serving-proxy
    apiVersion: v1
  fieldref:
    fieldpath: data.proxy_http
- name: https_proxy
  objref:
    kind: ConfigMap
    name: knative-serving-proxy
    apiVersion: v1
  fieldref:
    fieldpath: data.proxy_https
- name: no_proxy
  objref:
    kind: ConfigMap
    name: knative-serving-proxy
    apiVersion: v1
  fieldref:
    fieldpath: data.proxy_no
configurations:
- params.yaml
