apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
- namespace.yaml
- crds.yaml
- deployment.yaml
- service.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: quay.io/dexidp/dex
  newName: $(airgapRegistry)quay.io/dexidp/dex
  newTag: v2.24.0

secretGenerator:
- name: dex-oidc-client
  type: Opaque
  envs:
  - secret_params.env

configMapGenerator:
- name: dex-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: dex-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml