apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
commonLabels:
  app: tf-job-operator
  kustomize.component: tf-job-operator
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/name: tf-job-operator

configMapGenerator:
- name: tf-job-operator-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: tf-job-operator-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- params.yaml

images:
- name: public.ecr.aws/j1r0q0g6/training/tf-operator
  newName: $(airgapRegistry)public.ecr.aws/j1r0q0g6/training/tf-operator
  newTag: cd2fc1ff397b1f349f68524f4abd5013a32e3033