apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../image-pull-secret
namespace: kubeflow
patchesStrategicMerge:
- patches/remove-namespace.yaml
configMapGenerator:
- name: config
  behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
