apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/installs/generic
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/namespace
  - ../../third-party/mysql/base

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

configMapGenerator:
- name: pipeline-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: pipeline-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
